"""add is_offline

Revision ID: a3ff5124c7fb
Revises: 2e74c987acb6
Create Date: 2020-02-20 14:03:56.266242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ff5124c7fb'
down_revision = '2e74c987acb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_offline', sa.Boolean(),
                                     nullable=False,
                                     server_default='1'))
    op.create_index(op.f('ix_files_is_offline'), 'files', ['is_offline'],
                    unique=False)
    op.add_column('files', sa.Column('toggle_offline', sa.Boolean(),
                                     nullable=False,
                                     server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_is_offline'), table_name='files')
    op.drop_column('files', 'is_offline')
    op.drop_column('files', 'toggle_offline')
    # ### end Alembic commands ###
